Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -59,7 +59,8 @@ jobs:
 
       # Verify lcov installation
       - name: Verify lcov installation
-        run: perl $HOME/perl/bin/lcov --version || echo "lcov not found"
+        run: /usr/bin/perl $HOME/perl/bin/lcov --version || echo "lcov not found"
+
         
 
       # Set reusable strings
