Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -40,7 +40,11 @@ jobs:
 
       # Verify Perl installation
       - name: Verify Perl installation
-        run: perl --version || echo "Perl not found"
+        run: |
+          ls $HOME/perl/bin
+          perl --version || echo "Perl not found"
+
+     
 
       - name: Download and extract lcov
         run: |
